# Setup
title:               DevOpsChops Diaries
tagline:             'Notes from a developer of DevOps games'
description:         'Notes from a developer of DevOps games'
url:                 https://devopschops.com
baseurl:             '/blog'
paginate:            5
permalink:           pretty


# About/contact
author:
  name:              Laurence Tennant
  email:             admin@devopschops.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
