# Setup
title:               DevOpsChops Diaries
tagline:             'Notes from a developer of a DevOps game'
description:         'Notes from a developer of a DevOps game'
url:                 https://devopschops.com
baseurl:             ''
paginate:            5
permalink:           /blog/:title/


# About/contact
author:
  name:              Laurence Tennant
  email:             admin@devopschops.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-0VXHM1W3TE
